name: Code Style Check & Build

on: push

jobs:
  style-check:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      run: |
        if [ -d "c_repo" ]; then
          echo "If the directory exists, delete it"
          rm -rf "c_repo"
        fi
        git clone git@github.com:sengulhamza/c_repo.git

    - name: Code Style Check
      run : |
        cd c_repo/auth_with_cmac
        ./code-format.sh && git diff --exit-code
  build:
    needs: style-check
    runs-on: self-hosted
    steps:
    - name: Check gcc & cmake version
      run: |
        gcc --version
        cmake --version

    - name: Build Debug
      run: |
        cd c_repo/auth_with_cmac
        mkdir build
        cd build
        cmake ..
        make

    - name: Run
      run: |
        cd c_repo/frame_oop_with_crc/build
        ./auth_with_cmac

    - name: Clear cache and disk
      run : |
        sudo rm -r c_repo
