name: Code Style Check & Build

on: push

jobs:
  style-check:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      run: |
        if [ -d "c_repo" ]; then
          echo "If the directory exists, delete it"
          rm -rf "c_repo"
        fi
        git clone git@github.com:sengulhamza/c_repo.git

    - name: Code Style Check:auth_with_cmac
      run : |
        cd c_repo/auth_with_cmac
        ./code-format.sh && git diff --exit-code

    - name: Code Style Check:frame_oop_with_crc
      run : |
        cd c_repo/frame_oop_with_crc
        ./code-format.sh && git diff --exit-code

  build_debug:
    needs: style-check
    runs-on: self-hosted
    steps:
    - name: Check gcc & cmake version
      run: |
        gcc --version
        cmake --version

    - name: Build:auth_with_cmac
      run: |
        cd c_repo/auth_with_cmac
        mkdir build
        cd build
        cmake ..
        make

    - name: Build:frame_oop_with_crc
      run: |
        cd c_repo/frame_oop_with_crc
        make

  run_debug:
    needs: build_debug
    runs-on: self-hosted
    steps:
    - name: Run:auth_with_cmac
      run: |
        cd c_repo/auth_with_cmac/build
        ./auth_with_cmac

    - name: Run:frame_oop_with_crc
      run: |
        cd c_repo/frame_oop_with_crc
        ./frame_oop_with_crc

  clear_cache:
    needs: run_debug
    runs-on: self-hosted
    steps:
    - name: Clear cache and disk
      run : |
        sudo rm -r c_repo